/**
 * @packageDocumentation
 * @module api.functional.application_versions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as by_ids from "./by_ids";
